-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS status_values_kinds (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);
INSERT INTO status_values_kinds (id, name) VALUES (1, 'NEW'), (2, 'PROCESSING'), (3, 'INVALID'), (4, 'PROCESSED') ON CONFLICT DO NOTHING
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE status_values_kinds;
-- +goose StatementEnd
